---
version: 2.1

jobs:
  build:
    parameters:
      coq:
        type: string
    docker:
      - image: coqorg/coq:<<parameters.coq>>
    environment:
      OPAMJOBS: 2
      OPAMVERBOSE: 1
      OPAMYES: true
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Configure environment
          command: echo . ~/.profile >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
              opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
              opam update
              opam install coq-parsec coq-itree-io
      - run:
          name: List installed packages
          command: opam list
      - run:
          name: Compile
          command: |
            make -j`nproc` -C cas
            make -j`nproc` -C echo
            make -j`nproc` -C backtrack

workflows:
  version: 2
  test:
    jobs:
      - build:
          name: Coq 8.11
          coq: '8.11'
      - build:
          name: Coq 8.12
          coq: '8.12'
      - build:
          name: Coq 8.13
          coq: '8.13'
      - build:
          name: Coq dev
          coq: 'dev'
